name: Run Tests
on:
   pull_request:
      branches:
         - main
   workflow_call:
   workflow_dispatch:

jobs:
   test:
      runs-on: ubuntu-latest
      name: Run Tests
      env:
         TESTING: true
      steps:
         - name: Checkout Repository
           uses: actions/checkout@v2

         - name: Setup Python
           uses: actions/setup-python@v4
           with:
             python-version: '3.10.8'   # change to desired Python version

         - name: Setup Python Virtual Environment
           run: python -m venv python3-virtualenv

         - name: Install Dependencies
           run: python3-virtualenv/bin/pip install -r requirements.txt

         - name: Run Tests
           run: ./run_test.sh

         - name: Send Discord Success Message
           if: ${{ success() }}
           run: curl -s -X POST "${{ secrets.DISCORD_TESTING_WEBHOOK }}" -d "content=✅ Tests Passed! $(date +'%Y-%m-%dT%H:%M:%S')"

         - name: Send Discord Failure Message
           if: ${{ failure() }}
           run: curl -s -X POST "${{ secrets.DISCORD_TESTING_WEBHOOK }}" -d "content=❌ Tests Failed. $(date +'%Y-%m-%dT%H:%M:%S')"
